web:
  image: nginx
  ports:
    - "80:80"
fluent:
  build: td-agent
  volumes:
    - data:/data
  ports:
    - 24224
locust:
  build: locust
  command: locust -f scenarios.py -H http://web --no-web
  links:
    - web
    - fluent
  ports:
    - 24224
